### ISSUE TITLE
Console hangs on dry-run

### ISSUE THREAD

**Issue by sankethkatta** [db-migrate/node-db-migrate#343] opened 2016-01-23 02:28 UTC
When running with a `--dry-run` option, the SQL prints out, but the console hangs without ever exiting. 

Example with `--dry-run`:
```bash
$ db-migrate up --dry-run
[INFO] dry run
select version() as version;
SHOW search_path;
SET search_path TO "$user","public";
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public';
CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL);
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC;
BEGIN;;
received data: ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;
;
# continues to hang without exiting
```

Example without `--dry-run`:
```bash
$ db-migrate up
received data: ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

[INFO] Processed migration 20160118173511-address
[INFO] Done
$ # exits normally
```

**Comment by wzrdtales** [comment] 2016-01-23 09:10
Please always provide all necessary information to reproduce your issue:

Used
-db-migrate version
- driver and the version of the driver
- node version
- npm version

And always post the verbose run, never a non verbose. If needed also include example migrations that reproduce the failure on your side.

thank you

**Comment by sankethkatta** [comment] 2016-01-24 23:03
Here are some more details:

+ **db-migrate version**: 0.10.0-beta.7
+ **driver**: postgres
+ **db-migrate-pg version**: 0.1.7
+ **node version**: 4.2.6
+ **npm version**: 2.14.12

Steps to reproduce:

#### 1. Install `db-migrate` and `db-migrate-pg` at the above versions:

```bash
npm install db-migrate@0.10.0-beta.7
npm install db-migrate-pg@0.1.7
```

#### 2. Setup a `database.json` file:

```json
{
  "development": {
    "user": "postgres",
    "database": "test",
    "password": "test",
    "host": "localhost",
    "port": 5432,
    "driver": "postgres"
  }
}
```

#### 3. Create sql migration files:

```bash
$ db-migrate create --sql-file person
[INFO] Created migration at /home/sankethkatta/db-migrate-test/migrations/20160124224020-person.js
[INFO] Created migration up sql file at /home/sankethkatta/db-migrate-test/migrations/sqls/20160124224020-person-up.sql
[INFO] Created migration down sql file at /home/sankethkatta/db-migrate-test/migrations/sqls/20160124224020-person-down.sql
```

#### 4. Edit the up and down files:

_20160124224020-person-up.sql_:
```sql
ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;
```

_20160124224020-person-down.sql_:
```sql
ALTER TABLE person DROP COLUMN address;
```

#### 5. Test the migration with a dry run, which hangs:

```bash
$ db-migrate up --dry-run --verbose
[INFO] Detected and using the projects local version of db-migrate. '/home/sankethkatta/db-migrate-test/node_modules/db-migrate/index.js'
[INFO] dry run
[INFO] Using development settings: { user: 'postgres',
  database: 'test',
  password: '******',
  host: 'localhost',
  port: 5432,
  driver: 'postgres' }
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
select version() as version;
[SQL] SHOW search_path
SHOW search_path;
[SQL] SET search_path TO "$user","public"
SET search_path TO "$user","public";
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public';
[INFO] migration table created
[INFO] loading migrations from dir /home/sankethkatta/db-migrate-test/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC;
[INFO] preparing to run up migration: 20160124224020-person
[SQL] BEGIN;
BEGIN;;
received data: ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

[SQL] ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;
;
# continues to hang without exiting
```

**Comment by wzrdtales** [comment] 2016-01-25 07:36
Thank you!

I will take a look at it ASAP.

**Comment by wzrdtales** [comment] 2016-01-25 07:52
Ok, with that followed I wasn't able to reproduce this:

```
:node-db-migrate|v0.10.x $%]$ bin/db-migrate create up --dry-run --verbose
[INFO] dry run
[INFO] Using dev settings: { host: 'localhost',
  user: 'root',
  password: '******',
  database: 'mbt',
  driver: 'pg',
  multipleStatements: true }
[INFO] Created migration at /home/tobi/dbmigrate/node-db-migrate/migrations/20160125074201-up.js
```

Have you tried your described steps yourself, for me it works, maybe also OS dependent, here are my versions:

```
:node-db-migrate|v0.10.x $%]$ node -v && npm -v && bin/db-migrate --version && grep version node_modules/db-migrate-pg/package.json | awk -F'"' '$0=$4'
v4.2.6
2.14.12
0.10.0-beta.7
0.1.7
```

Maybe also your migrations are broken, maybe try recreate them.

**Comment by wzrdtales** [comment] 2016-01-25 07:54
Nevermind, just saw that I have left the `create` there, I need  to go for now, I take a look later again!

**Comment by wzrdtales** [comment] 2016-01-25 13:32
Ok, looked again and identified the bug!

This is due to changes to have backward compatible change towards promises. This currently done like this:
https://github.com/db-migrate/node-db-migrate/blob/master/lib/skeleton.js#L76

Actually it checks if the parameter is undefined, this do not work for this case, I followed back by then the advice:

> You shouldn't - instead call Promise.resolve(x) (Q(x) in Q) that will always convert any value or external thenable into a trusted promise. It is safer and easier than performing these checks yourself. 

Well, it turns out now that it is better to check myself instead of resolving it. A quick look at bluebird brings me to the decision that I'm going to do the same done here: 

https://github.com/petkaantonov/bluebird/blob/master/src/promise.js#L188-L197

Fix is incoming though.

**Closed** 2016-01-25 13:34 UTC
Labels: bug

**Comment by wzrdtales** [comment] 2016-01-25 14:54
Published as + db-migrate@0.10.0-beta.8

**Comment by sankethkatta** [comment] 2016-01-25 17:25
Thanks for the quick commits! Greatly appreciated. 

Did the changes solve the problems for you? I am still facing issues with the dry-run and the hanging problem still presents itself. I ran all commands in verbose, so the below logs are bit long. 

#### 1. I followed the same installation instructions as above:

Only difference is I install `0.10.0-beta.8` from git as it is not on npm yet.

```bash
npm install https://github.com/db-migrate/node-db-migrate.git#v0.10.0-beta.8
npm install db-migrate-pg@0.1.7
```

#### 2. Attempt to dry-run the migration:

Follow the same sql-file creation steps and configuration setup as above. Then attempt the dry-run, which results in a new error below:

```bash
$ db-migrate up --dry-run --verbose
[INFO] Detected and using the projects local version of db-migrate. '/home/sankethkatta/db-migrate-test/node_modules/db-migrate/index.js'
[INFO] dry run
[INFO] Using development settings: { user: 'postgres',
  database: 'test',
  password: '******',
  host: 'localhost',
  port: 5432,
  driver: 'postgres' }
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
select version() as version;
[SQL] SHOW search_path
SHOW search_path;
[SQL] SET search_path TO "$user","public"
SET search_path TO "$user","public";
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public';
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL)
CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL);
[INFO] migration table created
[INFO] loading migrations from dir /home/sankethkatta/db-migrate-test/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC;
[INFO] preparing to run up migration: 20160125165835-person
[SQL] BEGIN;
BEGIN;;
received data: ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

[SQL] ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;
;
[SQL] INSERT INTO "migrations" ("name", "run_on") VALUES ($1, $2) [ [ '/20160125165835-person',
    Mon Jan 25 2016 08:59:14 GMT-0800 (PST) ] ]
INSERT INTO "migrations" ("name", "run_on") VALUES ($1, $2) [ [ '/20160125165835-person',
    Mon Jan 25 2016 08:59:14 GMT-0800 (PST) ] ]
[INFO] Processed migration 20160125165835-person
[SQL] COMMIT;
COMMIT;;
[INFO] Done
[ERROR] TypeError: Cannot read property 'driver' of undefined
    at onComplete (/home/sankethkatta/db-migrate-test/node_modules/db-migrate/api.js:867:11)
    at /home/sankethkatta/db-migrate-test/node_modules/db-migrate/api.js:888:7
    at tryCatcher (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromiseAtPostResolution (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

#### 3. Try to run an real up migration:

First, create the "person" table so that the migration will run:

```bash
psql -U postgres test
test=# CREATE TABLE person (name VARCHAR(255));
CREATE TABLE
```

Then, run the migration:

```bash
$ db-migrate up --verbose
[INFO] Detected and using the projects local version of db-migrate. '/home/sankethkatta/db-migrate-test/node_modules/db-migrate/index.js'
[INFO] Using development settings: { user: 'postgres',
  database: 'test',
  password: '******',
  host: 'localhost',
  port: 5432,
  driver: 'postgres' }
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "$user","public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS "migrations" ("id"   SERIAL PRIMARY KEY NOT NULL, "name" VARCHAR (255) NOT NULL, "run_on" TIMESTAMP  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /home/sankethkatta/db-migrate-test/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20160125165835-person
[SQL] BEGIN;
received data: ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

[SQL] ALTER TABLE person ADD COLUMN address TEXT DEFAULT NULL;

[SQL] INSERT INTO "migrations" ("name", "run_on") VALUES ($1, $2) [ [ '/20160125165835-person',
    Mon Jan 25 2016 09:17:19 GMT-0800 (PST) ] ]
[INFO] Processed migration 20160125165835-person
[SQL] COMMIT;
[INFO] Done
[ERROR] TypeError: Cannot read property 'driver' of undefined
    at onComplete (/home/sankethkatta/db-migrate-test/node_modules/db-migrate/api.js:867:11)
    at /home/sankethkatta/db-migrate-test/node_modules/db-migrate/api.js:888:7
    at tryCatcher (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromiseAtPostResolution (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/sankethkatta/db-migrate-test/node_modules/db-migrate-pg/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The migration gets applied, but still throws the same error.

#### 4. Finally, I do a dry-run of the down migration, and the console hangs:

```bash
$ db-migrate down --dry-run --verbose                                                       
[INFO] Detected and using the projects local version of db-migrate. '/home/sankethkatta/db-migrate-test/node_modules/db-migrate/index.js'
[INFO] dry run
[INFO] Using development settings: { user: 'postgres',
  database: 'test',
  password: '******',
  host: 'localhost',
  port: 5432,
  driver: 'postgres' }
[INFO] Defaulting to running 1 down migration.
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
select version() as version;
[SQL] SHOW search_path
SHOW search_path;
[SQL] SET search_path TO "$user","public"
SET search_path TO "$user","public";
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public';
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC;
[INFO] preparing to run down migration: 20160125165835-person
[SQL] BEGIN;
BEGIN;;
received data: ALTER TABLE person DROP COLUMN address;

[SQL] ALTER TABLE person DROP COLUMN address;

ALTER TABLE person DROP COLUMN address;
;
# continues to hang without exiting
```

**Comment by wzrdtales** [comment] 2016-01-25 18:04
Yes you're right, this slipped through somehow. Pushing a hotfix out for this, just waiting for travis right now.

**Comment by wzrdtales** [comment] 2016-01-25 18:05
Thanks for reporting btw!

**Comment by wzrdtales** [comment] 2016-01-25 18:24
published as 
+ db-migrate@0.10.0-beta.9

**Comment by sankethkatta** [comment] 2016-01-25 20:08
Thanks again! It fixed the issues for up dry run migrations. I was still getting the hanging on down migrations though, but I think I found the culprit there. I sent a PR: https://github.com/db-migrate/node-db-migrate/pull/344

Looks like one of the conditions were missed in one of the previous commits.

**Comment by wzrdtales** [comment] 2016-01-25 23:17
Thank you!
