### ISSUE TITLE
Migration table not created in designated schema

### ISSUE THREAD

**Issue by ice2morrow** [db-migrate/node-db-migrate#288] opened 2015-08-07 21:43 UTC
The migration table is created inside the public schema regardless of the schema defined in the database config file when migrating to redshift. I want to be able to house multiple schemas on the same DB in redshift, and have separate migrations per schema. Is this possible?

Below is the verbose output from db-migrate when performing a migration on a redshift database: 

[INFO] connected
Inside create migrations table
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "dev","$user"," public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations'
[INFO] migration table created
[INFO] loading migrations from dir /Users/Josh/Projects/Compass.Web/database/migrations/warehouse
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[INFO] No migrations to run
[INFO] Done

It looks like it captured the schema, and sets the search path to it, but then doesn't pick up the correct migration table.

**Comment by wzrdtales** [comment] 2015-08-07 21:58
Please provide all necessary informations to reproduce this.

I'm currently missing:
db-migrate version used,
node version used

**Comment by wzrdtales** [comment] 2015-08-07 22:06
Also I could be wrong, but I think this problem was also solved in the new version which was released today (v0.9.19), which includes the following bugfix which I merged today:

#287 

Please always include the version information and all necessary informations to complete reproduce the issue. So we can help you way faster, without having to guess and collect data :)

**Comment by ice2morrow** [comment] 2015-08-10 14:14
@wzrdtales You are correct, this is basic information that I did not mean to leave out.

Node version - 0.10.38
db-migrate version - 0.9.19 (as of the last time I tried this, and it still did not work).

Below is the error printed:

```
Migrate failed:  { [Error: Command failed: [ERROR] error: Column "migrations.id" has unsupported type "serial".
    at Connection.parseE (/Users/jclaus/Documents/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/jclaus/Documents/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/jclaus/Documents/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
] killed: false, code: 1, signal: null }
```

Redshift does not support a serial column type, so ahead of time I tried creating the migrations table myself with correct column type (identity), and then hoping db-migrate could use it. Then I got this:

```
 ERROR:  [ERROR] error: relation "migrations" does not exist
    at Connection.parseE (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

**Comment by wzrdtales** [comment] 2015-08-10 19:27
Ok, this is strange. I know from the issue #277 that migrations do work on redshift. This means something has changed somewhere. It's a bit tricky to figure this out, as I can't test it locally...

The second error, comes directly from the pg driver and not from db-migrate though. Seems like the table can't be found?
To the first error:
This is indeed strange, as you can see yourself from the linked issue, this has worked on redshift. 

So we **do** need the serial type, which is used for the "autoincrement":
```
'id': { type: type.INTEGER, notNull: true, primaryKey: true, autoIncrement: true },
```

Just having a quick look at the docs:
http://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html

Well ok, the pendant to autoIncrement for redshift seems to be IDENTITY. Uff, I hate it when developer split off from the original product that hard and dropping support of essential features... .

I see were we need to go though...
We need an additional driver, one that is basically one to one the pg driver, but with some minor changes. Like using IDENTITY for our auto incremented id column.
Actually I have a big problem with this:
I can't run this on our CI and thus can't test it properly and it doesn't seem like amazon would provide binaries...

**Comment by wzrdtales** [comment] 2015-08-10 20:07
@ice2morrow lets focus on the second error first. Can you somehow ensure that in the schema the migration table exists (with the identity instead of serial), maybe you created it in the wrong schema?

The error: `relation "migrations" does not exist` is mostly related to a missing table, or insufficent permissions.

**Comment by ice2morrow** [comment] 2015-08-10 22:08
@wzrdtales I can confirm the table is there, and with the correct column type when I create it manually. If I leave it to db-migrate, its created, but with the wrong column type, which throws the error.

**Comment by wzrdtales** [comment] 2015-08-10 22:16
@ice2morrow Then please do the following, get the queries generated by db-migrate through the verbose mode. And try executing them one by one manually and try to figure out where exactly the problem is.

As pointed out, this could also be a problem with missing permissions, which would cause a `relation "" does not exist` failure.

Can you also try version 0.9.17, with the migration table manually created. Just to make sure, there wasn't introduce a bug and we search at the wrong place...

Thank you

**Comment by wzrdtales** [comment] 2015-08-12 09:41
@ice2morrow Just to inforn you:
I will pick up this task for the redshift driver, which is going to use IDENTITY instead of SERIAL after I have finished on the linking between VC Seeders and Migrations.

Did you already had some time to try the queries manually, to discover where exactly everything stucks?

**Comment by ice2morrow** [comment] 2015-08-12 14:34
@wzrdtales I did what you asked, downgrading to 0.9.17 first, listed is the verbose output:

```
[INFO] Using dev settings: { driver: 'pg',
  database: '***',
  host: '***',
  port: '***',
  user: '***',
  password: '******',
  schema: 'dev' }
[INFO] require: ./pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "dev","$user"," public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'dev'
[INFO] migration table created
[INFO] loading migrations from dir /Users/Josh/Projects/Compass.Web/database/migrations/warehouse
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[ERROR] error: relation "migrations" does not exist
    at Connection.parseE (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

Then I ran them manually: 
```
SHOW search_path;
$user, public
SET search_path TO "dev","$user", "public"
ran ok
SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'dev'
came back with one row {table_name: 'migrations'}
SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
came back empty
```

The results were the same on both versions but below is the stacktrace from 0.9.19:
```
[INFO] require: ./pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "dev","$user"," public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'dev'
[INFO] migration table created
[INFO] loading migrations from dir /Users/Josh/Projects/Compass.Web/database/migrations/warehouse
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[ERROR] error: relation "migrations" does not exist
    at Connection.parseE (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/Josh/Projects/Compass.Web/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

**Comment by wzrdtales** [comment] 2015-08-12 15:01
@ice2morrow Ok good, then this is nothing that was introduced with any of the last patches. Good to know!

So the node-pg driver (not the db-migrate pg driver) is returning the error at 
   
     SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC

Nothing new so far..., next question is:
Did you executed the queries with the same credentials you used in your database.json config for db-migrate? As the commands all ran fine while executing them manually, that could be also related to different permissions.

And concerning "came back empty", also try to insert some records into the migrations table.

**Comment by wzrdtales** [comment] 2015-08-12 15:13
@ice2morrow I think I have found the failure:

    [SQL] SET search_path TO "dev","$user"," public"

Watching this cloooooosely, makes us aware of an space before public..

There was a pull request, for a similar bug that made it into the master concerning postrgresql 9.5 alhpa #282. Seems like the amazon devs are porting some buggy features. Going to release a patch for this.

**Comment by wzrdtales** [comment] 2015-08-12 15:20
Waiting for tag passing tests:
https://travis-ci.org/db-migrate/node-db-migrate/builds/75284843

**Comment by wzrdtales** [comment] 2015-08-12 15:26
Tag has passed the tests.

Released new patch v0.9.20.

Closed the issue, please try it with the newest version and reopen of necessary.

**Closed by wzrdtales** 2015-08-12 15:26 UTC
Labels: question

**Comment by wzrdtales** [comment] 2015-08-12 23:03
Added Issue concerning the issue with the SERIAL datatype.

@ice2morrow Did the released fix work for you?

**Comment by ice2morrow** [comment] 2015-08-12 23:06
@wzrdtales It looks like it did, thank you very much

**Comment by wzrdtales** [comment] 2015-08-12 23:07
Great, looking forward to create a better support for redshift, thus you and no one else have to create the migration table by hand :)
