### ISSUE TITLE
`DATABASE_URL` support

### ISSUE THREAD

**Issue by jney** [db-migrate/node-db-migrate#337] opened 2016-01-17 16:40 UTC
As i read the doc `DATABASE_URL` env var is supported.
But, using `db-migrate` i accountered some awkward behaviours. Or i missed something.
 
```
$ echo $DATABASE_URL
postgres://postgres@0.0.0.0:5432/test
$ ./node_modules/.bin/db-migrate db:create
[INFO] Error: You must enter a database name!
```

At this point, why should i declare the db name as it is already explicitly declared in the `DATABASE_URL` var ?

```
$ ./node_modules/.bin/db-migrate db:create test
[ERROR] error: database "test" does not exist
  at [object Object].Connection.parseE (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
  at [object Object].Connection.parseMessage (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
  at Socket.<anonymous> (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

Sure `test` does exist, i'm trying to create it.

**Comment by wzrdtales** [comment] 2016-01-17 17:59
Please provide the information you get from the verbose run. You start the verbose run by appending `-v` as parameter.

**Comment by wzrdtales** [comment] 2016-01-17 18:03
Also to add, if test wouldn't exist, this error wouldn't be thrown. If it already exists there is no need for you to execute this command.

And about the specified db, no this is not the way how this command should work. You're creating a new database with this command, while the configuration expects that this already exists. Thus this is clearly out of scope for db:create, maybe we can additionally add something like db:init, as this is initialization you talk about.

**Comment by wzrdtales** [comment] 2016-01-17 18:04
And last but not least, also always provide:

Used
- node version
- npm version
- db-migrate version

**Comment by jney** [comment] 2016-01-17 18:05
```
./node_modules/.bin/db-migrate -v db:create test
[INFO] Using urlConfig settings: { driver: 'postgres',
  user: 'postgres',
  database: 'test',
  host: '0.0.0.0',
  port: '5432' }
[INFO] require: ./postgres
[INFO] connecting
[INFO] connected
[SQL] CREATE DATABASE "test"
[ERROR] error: database "test" does not exist
  at [object Object].Connection.parseE (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:534:11)
  at [object Object].Connection.parseMessage (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:361:17)
  at Socket.<anonymous> (/home/me/src/project/node_modules/db-migrate/node_modules/pg/lib/connection.js:105:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

**Comment by wzrdtales** [comment] 2016-01-17 18:08
Yes, as suspected nothing wrong with this, `test` clearly already exists. Just don't use create if this already exists. This information also does not come from db-migrate, but the driver itself, db-migrate did its job to completion.

**Comment by jney** [comment] 2016-01-17 18:35
@wzrdtales i don't get it the previous  message clearly says `[ERROR] error: database "test" does not exist` and : 

```
$ psql postgres://postgres@0.0.0.0:5432/test
psql: FATAL:  database "test" does not exist
```

**Comment by wzrdtales** [comment] 2016-01-17 18:43
oh, ok, really have not seen the not. This is because db-migrate always tries to connect to a database specified. This error is caused by your provided url which tries to connect to test. This is something that needs to be added, but in this case this is probably still an init instead of a create operation. Nevertheless, to have command execution supported without actually connecting to a database is in some cases not that unproblematic.
In case of MySQL/MariaDB this is easy, connecting without a database specified is not a problem at all. But for example postgres does always connect to  some db. If no db is specified it uses the username of the executing user. Thus this probably has to be the default database that always exists.

**Comment by wzrdtales** [comment] 2016-01-17 19:04
@jney I have opened this as issue(task), #338.

**Comment by wzrdtales** [comment] 2016-01-17 19:26
@jney Convinience feature for initialization also added as issue(task), #339

**Comment by wzrdtales** [comment] 2016-01-17 19:27
Closing this issue from here with thoe new items in place.

**Closed by wzrdtales** 2016-01-17 19:27 UTC
Labels: question

**Comment by jney** [comment] 2016-01-17 19:37
thank you :+1:
