### ISSUE TITLE
command db-migrate up 20150207135259-myFancyMigration runs all migrations

### ISSUE THREAD

**Issue by rwollgar** [db-migrate/node-db-migrate#412] opened 2016-09-16 01:24 UTC
Hi,

I can't run a specific migration using the following command:
db-migrate up 20150207135259-myFancyMigration

db-migrate always runs all migrations.

**Comment by wzrdtales** [comment] 2016-09-16 07:33
Please always post **all** necessary information. Otherwise we won't be able to help you.

Please post:
 - db-migrate version
 - node version
 - npm version
 - used driver + version
 - verbose run log

Thank you

**Comment by rwollgar** [comment] 2016-09-19 01:43
db-migrate version: 0.10.0-beta.16
node version: 6.3.1
npm version: 3.10.3
drivers: pg (0.1.10) and redshift (0.0.2)
run log:

Trying to run only 20160906025331-misc, but also runs: 20160902055347-billing

db-migrate up 20160906025331-misc --verbose --env testlocal
[INFO] Detected and using the projects local version of db-migrate. 'C:\gitrepos\streamco-redshiftify\node_modules\db-migrate\index.js'
[INFO] Using testlocal settings: { driver: 'pg',
  user: 'postgres',
  password: '******',
  host: 'localhost',
  port: 5432,
  database: 'rstest' }
[INFO] require: db-migrate-pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "$user","public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
[INFO] migration table created
[INFO] loading migrations from dir C:\gitrepos\<>\migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20160902055347-billing
[SQL] BEGIN;
[INFO] creating table: table1
[SQL] CREATE TABLE "table1" ...
[INFO] creating table: table2
[SQL] CREATE TABLE  "table2" ...
[INFO] Processed migration 20160902055347-billing
[SQL] COMMIT;
[INFO] preparing to run up migration: 20160906025331-misc
[SQL] BEGIN;
[INFO] creating table: misc1
[SQL] CREATE TABLE  "misc1" ...
[INFO] creating table: misc2
[SQL] CREATE TABLE  "misc2" ...
[INFO] Processed migration 20160906025331-misc
[SQL] COMMIT;
[INFO] Done

**Comment by wzrdtales** [comment] 2016-09-19 06:38
@rwollgar Not a bug, and nothing surprising here. `20160902055347` is earlier than `20160906025331`. If you specify a migration, db-migrate use your specified migration as a target. This is the one and only way db-migrate is going to behave and this also wont change. This is how migrations work, you don't want to execute any migration, before migrations that are earlier in the order have been executed. If you want to really only execute your migration, then you either doing it wrong or just should migrate up to the migration you want to execute first.

**Comment by wzrdtales** [comment] 2016-09-19 06:38
Closing here as this is not a bug, but feel free to comment or ask if you have any other questions.

**Closed by wzrdtales** 2016-09-19 06:38 UTC
