### ISSUE TITLE
Question about using the "all" scope

### ISSUE THREAD

**Issue by sa-eneidhart** [db-migrate/node-db-migrate#489] opened 2017-08-14 19:45 UTC
I'm not sure if I'm doing something wrong, or if I actually hit a bug. I'm trying to run `db-migrate up:all`, and the console seems to hang. Verbose output:

    MBP15-SG8WP:engagement eneidhart$ db-migrate up:all -v
    [INFO] Detected and using the projects local version of db-migrate. 
    '/Users/eneidhart/git/engagement/node_modules/db-migrate/index.js'
     [INFO] Using dev settings: { driver: 'mongodb',
      database: 'test',
      host: 'localhost',
      port: 29017 }
    [INFO] require: db-migrate-mongodb
    [INFO] connecting
    [INFO] SSH tunnel connected on port  27017
    [INFO] connected
    [INFO] Enter scope "/"
    [SQL] use [ 'test' ]

I'm especially confused by `[INFO] Enter scope "/"`. Isn't the point of `:all` that I shouldn't need to enter any scope, because it runs on all of them? Even so, I've tried entering pretty much anything I can think of, to no avail; the console just hangs at this point. 

This seems to be the only documented command I'm having trouble running; I could run migrations from any of my scopes individually if I wish. I feel I should note that all my configuration is in `database.json`, and that I have migrations in the default scope as well as 2 other scopes.

More relevant info:

- node v6.10.2
- npm 3.10.10
- db-migrate 0.10.0-beta.21
- db-migrate-mongodb 1.2.2

**Comment by wzrdtales** [comment] 2017-08-14 19:57
> I'm especially confused by [INFO] Enter scope "/". Isn't the point of :all that I shouldn't need to enter any scope, because it runs on all of them?

Shouldn't be confusing. You're completely right and db-migrate just tells you that it does esactly what you asked it to. Move through all scopes and execute them.

Could you provide me an example with a set of migrations to reproduce this?

**Comment by sa-eneidhart** [comment] 2017-08-14 20:03
My migrations are all pretty basic, as I'm just kinda testing out the functionality for myself at this point. They all look more or less like this:

    exports.up = function(db) {
      return db.createCollection('mycollection');
    };

    exports.down = function(db) {
      return db.dropCollection('mycollection');
    };

**Comment by wzrdtales** [comment] 2017-08-14 20:20
Seems to be a driver problem in this case. It assumes an async operation, which turns out to actually not be one:

http://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#db

Gonna look to put out a fix for this.

**Comment by sa-eneidhart** [comment] 2017-08-14 20:23
Thanks for your help! :)

**Comment by wzrdtales** [comment] 2017-08-14 20:29
I pushed out a patch for the mongodb driver, should be fixed now.

**Closed by wzrdtales** 2017-08-14 20:29 UTC
