### ISSUE TITLE
Cannot add a foreign key while adding a column

### ISSUE THREAD

**Issue by benbotto** [db-migrate/node-db-migrate#407] opened 2016-08-27 16:48 UTC
This report is against db-migrate version 0.9.x (latest), using the mysql driver.  I'm unable to use foreign key definitions when adding a column in a migration, although an identical foreign key definition works correctly in a table-creation migration.
 
Consider the following table creation:

```javascript
'use strict';

exports.up = function(db, callback) {
  db.createTable('UsersGamesThrows', {
    userGameThrowID: {
      type: 'int',
      notNull: true,
      primaryKey: true,
      autoIncrement: true
    },
    // Foreign keys work fine when creating a table.
    /*userGameID: {
      type: 'int',
      notNull: true,
      foreignKey: {
        name: 'UsersGames_userGameID_fk',
        table: 'UsersGames',
        mapping: 'userGameID',
        rules: {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        }
      }
    },*/
    // [... More columns ...]
  }, callback);
};

exports.down = function(db, callback) {
  db.dropTable('UsersGamesThrows', callback);
};
```

Now I'd like to add a column that reference another table in a second migration:

```javascript
exports.up = function(db, callback) {
  db.addColumn('UsersGamesThrows', 'userGameID',
    {
      type: 'int',
      notNull: true,
      foreignKey: {
        name: 'UsersGames_userGameID_fk',
        table: 'UsersGames',
        mapping: 'userGameID',
        rules: {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        }
      }
    }, callback);
};

exports.down = function(db, callback) {
  db.removeColumn('UsersGamesThrows', 'userGameID', callback);
};
```
Note that the foreign key definition is identical to that in the create script (it's commented out), but the constraint fails in the addColumn method:

```
[INFO] Using dev settings: { driver: 'mysql',
  user: 'dg-user',
  password: '******',
  database: 'disc_golf_tracker' }
[INFO] require: ./mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /home/avejidah/dev/disc-golf-tracker/api/db/migration
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20160826221323-add-userGameID-to-usersGamesThrows
[SQL] ALTER TABLE `UsersGamesThrows` ADD COLUMN `userGameID` INTEGER  NOT NULL
[SQL] ALTER TABLE `undefined` ADD CONSTRAINT `UsersGamesThrows_userGameID_fk` FOREIGN KEY (`userGameID`) REFERENCES `UsersGames` (`userGameID`) ON DELETE CASCADE ON UPDATE RESTRICT
[ERROR] Error: ER_NO_SUCH_TABLE: Table 'disc_golf_tracker.undefined' doesn't exist
    at Query.Sequence._packetToError (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/Connection.js:214:25)
    at Class.Base.extend.runSql (/home/avejidah/dev/disc-golf-tracker/node_modules/db-migrate/lib/driver/mysql.js:395:34)
    at Class.Base.extend.addForeignKey (/home/avejidah/dev/disc-golf-tracker/node_modules/db-migrate/lib/driver/mysql.js:354:10)
    at Object.foreignKey (/home/avejidah/dev/disc-golf-tracker/node_modules/db-migrate/lib/driver/base.js:88:39)
    at Query._callback (/home/avejidah/dev/disc-golf-tracker/node_modules/db-migrate/lib/driver/mysql.js:183:13)
    at Query.Sequence.end (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query._handleFinalResultPacket (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/home/avejidah/dev/disc-golf-tracker/node_modules/mysql/lib/protocol/Protocol.js:280:23)
```

Note that the column gets added, but the script crashes on the constraint creation.  The result is such that the migration is partially complete, but the migration table has not been updated.  The user is left with a manual rollback.

Thanks,

[b]

**Comment by wzrdtales** [comment] 2016-08-27 17:02
That seems to be something with the syntax as there gets an undefined thrown  `'disc_golf_tracker.undefined'`. But from your example on the first look everything looks ok though.

Could you provide a complete executable example that reproduce your behavior, with the two tables being created and your foreignKey specification? Best create a gist for this, that would really help me to reproduce and help you, while if I need to recreate everything myself you probably need to wait until I get some more time though.

Thank you

**Comment by wzrdtales** [comment] 2016-08-27 17:12
Ok, I just tried quickly your addColumn example you've posted.

Two things:

This is already fixed in the latest 0.10.x tree, if you worry about the beta version, it is not so beta anymore though. But I keep that to you what you want to use.

The problem lays however here:

https://github.com/db-migrate/node-db-migrate/blob/v0.9.x/lib/driver/mysql.js#L178


Thus foreignKey definitions do work in `createTable` functions but not in `addColumn` on the current v0.9.x tree.

**Comment by benbotto** [comment] 2016-08-27 17:17
Hi wzrdtales,

Thanks for the quick response.  I was just putting together a gist but it looks like you beat me to it and tracked down the problem.

I'll try to move to 0.10.x as suggested.  Thus far 0.9.x has been working well for me, so I haven't had a reason to update.  It looks like now's the time, though.

Thanks again,

[b]

**Comment by wzrdtales** [comment] 2016-08-27 17:36
No problem, 0.9.x is working though, 0.10.x adds much new stuff, like promise style migrations and much more though. You should note that you will need to install the driver although when switching to 0.10.x.

 Means e.g. `npm install db-migrate-mysql --save-dev`, after that everything should be like it was before. Also notice, db-migrate 0.10.x prefers your local installed version over the global one. That means if you have installed db-migrate as a dependency of your project, the global installation is going to chainload this instead.

Those might be the two big things you should know, though.

**Comment by wzrdtales** [comment] 2016-09-28 15:52
Was also backported to the latest 0.9.x track.

**Closed by wzrdtales** 2016-09-28 15:52 UTC
Labels: bug

**Comment by benbotto** [comment] 2016-09-28 15:55
Thank you!
